### ISSUE TITLE
[ENH]: Adding option to export/return PDB as a raw string

### ISSUE THREAD

**Issue by jbHedderich** [LBC-LNBio/pyKVFinder#112]
### Problem

It would be very useful to be able to return the cavities as a string in PDB format instead of immediately writing it to a file. 
Thanks a lot!

### Proposed solution

This should be done by editing the _export function, since the PDB string is anyways generated, right? Or are there any other possibilities that I am missing?

**Comment by jvsguerra** [comment]
Hi @jbHedderich,

Thank you for your suggestion.

Are you interested in obtaining the coordinates of the cavity points in PDB format as a string?

**Comment by jvsguerra** [comment]
I have implemented an option to export PDB as a raw string in [pyKVFinder v0.6.14](https://github.com/LBC-LNBio/pyKVFinder/releases/tag/v0.6.14).

Usage:

```python
>>> import pyKVFinder
>>> pdb = os.path.join(os.path.dirname(pyKVFinder.__file__), 'data', 'tests', '1FMO.pdb')
>>> results = pyKVFinder.run_workflow(pdb)
>>> string = results.export(None)
>>> print(string)
ATOM     1  H   KAA     0       0.000   0.000   0.000  1.00  0.00
...
ATOM  1000  H   KAA     0       0.000   0.000   0.000  1.00  0.00
>>> string = results.export_all(output=None)
>>> print(string)
ATOM     1  H   KAA     0       0.000   0.000   0.000  1.00  0.00
...
ATOM  1000  H   KAA     0       0.000   0.000   0.000  1.00  0.00
```

Alternatively:

```python
>>> import pyKVFinder
>>> pdb = os.path.join(os.path.dirname(pyKVFinder.__file__), 'data', 'tests', '1FMO.pdb')
>>> atomic = pyKVFinder.read_pdb(pdb)
>>> vertices = pyKVFinder.get_vertices(atomic)
>>> ncav, cavities = pyKVFinder.detect(atomic, vertices)
>>> string = pyKVFinder.export(None, cavities, None, vertices)
>>> print(string)
ATOM     1  H   KAA     0       0.000   0.000   0.000  1.00  0.00
...
ATOM  1000  H   KAA     0       0.000   0.000   0.000  1.00  0.00
```

Please let me know if this meets your needs. If you encounter any further issues or have additional questions, feel free to ask for assistance.

**Comment by jbHedderich** [comment]
Thanks, that helped a lot :)!
